web_application/web_application/urls.py
from django.contrib import admin
from django.urls import path
from web_app import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('emp', views.emp),
    path('show',views.show),
    path('edit/<int:id>', views.edit),
    path('update/<int:id>',views.update),
    path('delete/<int:id>',views.delete),
]

web_application/web_app/models.py
from django.db import models

# Create your models here.

class Employee(models.Model):
    employee_id = models.CharField(max_length=20)
    employee_name = models.CharField(max_length=30)
    employee_email = models.EmailField()
    employee_contact = models.CharField(max_length=15)


    class Meta:
        db_table="Employee"

web_application/web_app/forms.py
from django import forms
from web_app.models import Employee


class EmployeeForm(forms.ModelForm):
    class Meta:
        model= Employee
        fields="__all__"

web_application/web_app/views.py
from django.shortcuts import render,redirect
from web_app.forms import EmployeeForm
from web_app.models import Employee


# Create your views here.

def emp(request):
    if request.method=="POST":
        form = EmployeeForm(request.POST)
        if form.is_valid():
            try:
                form.save()
                return redirect("/show")
            except:
                pass
    else:
        form=EmployeeForm()
    return render(request,"index.html",{'form':form})


def show(request):
    employee= Employee.objects.all()
    return render(request,"show.html",{'employee':employee})

def edit(request,id):
    employee= Employee.objects.get(id=id)
    return render(request,"edit.html",{'employee':employee})

def update(request, id):
    employee= Employee.objects.get(id=id)
    form =EmployeeForm(request.POST,instance=Employee)
    if form.is_valid():
        form.save()
        return redirect("/show")
    return render(request,"edit.html", {'employee':employee})

def delete(request,id):
    employee = Employee.objects.get(id=id)
    employee.delete()
    return redirect("/show")

web_application/web_app/templates/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <link rel="stylesheet" href="{% static '/style.css' %}"/>
    <title>Index</title>
</head>
<body style="background-color:#a6c74c">

<form method="POST" class="post-form" action="/update/ {{employee.id}}">
    {% csrf_token %}
    <div class="container">
        <br>
        <div class="form-group row">
            <label class="col-sm-1 col-form-label"></label>
             <div class="col-sm-4">
             <h3>Update Details</h3>
            </div>
        </div>

        <div class="form-group row">
            <label class="col-sm-2 col-form-label">Epmloyee Id:</label>
             <div class="col-sm-4">
              <input type="text" name="employee_id" id="id_employee_id" value="{{employee.employee_id}}"/>
            </div>
        </div>

        <div class="form-group row">
            <label class="col-sm-2 col-form-label">Epmloyee Name:</label>
             <div class="col-sm-4">
              <input type="text" name="employee_name" id="id_employee_name" value="{{employee.employee_name}}"/>
            </div>
        </div>

        <div class="form-group row">
            <label class="col-sm-2 col-form-label">Epmloyee Email:</label>
             <div class="col-sm-4">
              <input type="text" name="employee_email" id="id_employee_email" value="{{employee.employee_email}}"/>
            </div>
        </div>


        <div class="form-group row">
            <label class="col-sm-2 col-form-label">Epmloyee Contact:</label>
             <div class="col-sm-4">
              <input type="text" name="employee_contact" id="id_employee_contact" value="{{employee.employee_contact}}"/>
            </div>
        </div>

        <div class="form-group row">
            <label class="col-sm-1 col-form-label"></label>
             <div class="col-sm-4">
             <button type="submit" class="btn btn-success">Update</button>
            </div>
        </div>

    </div>



 </form>

</body>
</html>

web_application/web_app/templates/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    <link rel="stylesheet" href="{% static '/style.css' %}"/>
    <title>Index</title>
</head>
<body style="background-color:#32ed96">

<form method="POST" class="post-form" action="/emp">
    {% csrf_token %}
    <div class="container">
        <br>
        <div class="form-group row">
            <label class="col-sm-1 col-form-label"></label>
             <div class="col-sm-4">
             <h3>Enter the Details</h3>
            </div>
        </div>

        <div class="form-group row">
            <label class="col-sm-2 col-form-label">Epmloyee Id:</label>
             <div class="col-sm-4">
              {{form.employee_id}}
            </div>
        </div>

        <div class="form-group row">
            <label class="col-sm-2 col-form-label">Epmloyee Name:</label>
             <div class="col-sm-4">
              {{form.employee_name}}
            </div>
        </div>

        <div class="form-group row">
            <label class="col-sm-2 col-form-label">Epmloyee Email:</label>
             <div class="col-sm-4">
              {{form.employee_email}}
            </div>
        </div>

        <div class="form-group row">
            <label class="col-sm-2 col-form-label">Epmloyee Contact:</label>
             <div class="col-sm-4">
              {{form.employee_contact}}
            </div>
        </div>
        <br>
        <div class="form-group row">
            <label class="col-sm-1 col-form-label"></label>
             <div class="col-sm-4">
             <button type="submit" class="btn btn-success">Submit</button>
            </div>
        </div>

    </div>
</form>

 </body>
 </html>

web_application/web_app/templates/show.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Employee Records</title>
    {% load static %}
    <link rel="stylesheet" href="{% static '/style.css' %}">
</head>
<body style="background-color:#6783a8">
   <table class="table table-striped table-bordered table-sm">
       <thead class="thead-dark">
        <tr>
           <th>Employee Id</th>
           <th>Employee name</th>
           <th>Employee Email</th>
           <th>Employee Contact</th>
           <th>Actions</th>
        </tr>
       </thead>
       <tbody>
       {% for employee in employee %}
         <tr>
             <td>{{ employee.employee_id }}</td>
             <td>{{ employee.employee_name }}</td>
             <td>{{ employee.employee_email }}</td>
             <td>{{ employee.employee_contact }}</td>
             <td>
                 <a href="/edit/{{employee.id}}"><span class="glyphicon glyphicon-pencil">Edit</span></a>
                 <a href="/delete/{{employee.id}}">Detele</a>
             </td>
         </tr>
       {% endfor %}
       </tbody>
   </table>
</body>
</html>